#!/bin/sh

# prettier
ADDED_FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.js" "*.ts" "*.tsx" | sed 's| |\\ |g')
if [ -n "$ADDED_FILES" ]
then
  echo "$ADDED_FILES" | xargs npx prettier --write
  echo "$ADDED_FILES" | xargs git add
fi

# confirm build
yarn build
if [ $? -ne 0 ]
then
  echo "git pre-commit check failed: build failed."
  exit 1
fi

exit 0
